# Generated by Django 3.1.7 on 2021-04-03 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('poll_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_poll', to='webapp.poll', verbose_name='Опрос')),
                ('possible_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_answer', to='webapp.choice', verbose_name='Вариант ответа')),
            ],
        ),
    ]
